<x-admin-layout title="{{ str($view)->headline() }} | Luckyboss Admin" heading="{{ str($view)->headline() }}">
    <p style="color:#667085">Live control-center data for {{ str($section)->headline() }}.</p>@if(session('success'))<p style="color:#027a48;font-weight:700">{{ session('success') }}</p>@endif
    @if(!empty($data['metrics']))<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin:18px 0">@foreach($data['metrics'] as $label=>$value)<article class="admin-card" style="padding:20px"><span style="color:#667085">{{ str($label)->headline() }}</span><strong style="display:block;margin-top:8px;font-size:27px">{{ is_numeric($value) ? number_format($value, 2) : $value }}</strong></article>@endforeach</div>@endif
    @if(isset($data['users']))<section class="admin-card" style="padding:8px 18px"><table class="admin-table"><thead><tr><th>User</th><th>Email</th><th>Roles</th><th>Status</th></tr></thead><tbody>@foreach($data['users'] as $user)<tr><td>{{ $user->name }}</td><td>{{ $user->email }}</td><td>{{ $user->roles->pluck('name')->join(', ') }}</td><td>{{ $user->is_active ? 'Active' : 'Blocked' }}</td></tr>@endforeach</tbody></table></section>
    @elseif(isset($data['permissions']) || (isset($data['records']) && $section === 'users-permissions'))<section class="admin-card" style="padding:8px 18px"><table class="admin-table"><thead><tr><th>Name</th><th>Module</th><th>Details</th></tr></thead><tbody>@foreach($data['records'] as $record)<tr><td>{{ $record->name }}</td><td>{{ $record->module ?? ($record->slug ?? '-') }}</td><td>{{ $record->description ?? ($record->users_count ?? '') }}</td></tr>@endforeach</tbody></table></section>
    @elseif(isset($data['security']))<section class="admin-card" style="padding:8px 18px"><table class="admin-table"><thead><tr><th>User</th><th>Event</th><th>IP</th><th>Time</th></tr></thead><tbody>@foreach($data['security'] as $log)<tr><td>{{ $log->user?->name ?: 'System' }}</td><td>{{ $log->event }}</td><td>{{ $log->ip_address ?: '-' }}</td><td>{{ $log->created_at->format('d M Y H:i') }}</td></tr>@endforeach</tbody></table>{{ $data['security']->links() }}</section>
    @elseif(isset($data['audit']))<section class="admin-card" style="padding:8px 18px"><table class="admin-table"><thead><tr><th>Action</th><th>User</th><th>Company</th><th>Entity</th><th>Time</th></tr></thead><tbody>@foreach($data['audit'] as $log)<tr><td>{{ $log->action }}</td><td>{{ $log->user?->name ?: 'System' }}</td><td>{{ $log->company?->name ?: '-' }}</td><td>{{ $log->entity_type ?: '-' }} #{{ $log->entity_id }}</td><td>{{ $log->created_at->format('d M Y H:i') }}</td></tr>@endforeach</tbody></table>{{ $data['audit']->links() }}</section>
    @else<form method="POST" action="{{ route('admin.control-center.records.store') }}" class="admin-card" style="display:grid;grid-template-columns:1fr 2fr auto;gap:12px;padding:16px;margin:18px 0">@csrf<input type="hidden" name="section" value="{{ $section }}"><input type="hidden" name="view" value="{{ $view }}"><input class="admin-input" style="margin:0" name="name" placeholder="Record name" required><input class="admin-input" style="margin:0" name="description" placeholder="Description"><button class="admin-button">Add record</button><textarea class="admin-input" style="grid-column:1/-1;margin:0" name="payload" placeholder="JSON payload" rows="4"></textarea></form><section class="admin-card" style="padding:8px 18px"><table class="admin-table"><thead><tr><th>Name</th><th>Description</th><th>Payload</th></tr></thead><tbody>@forelse($data['records'] ?? [] as $record)<tr><td>{{ $record->name }}</td><td>{{ $record->description ?: '-' }}</td><td>{{ json_encode($record->payload) }}</td></tr>@empty<tr><td colspan="3" style="padding:24px;color:#667085">No records configured.</td></tr>@endforelse</tbody></table></section>@endif
</x-admin-layout>
