<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('candidate_resumes', function (Blueprint $table) { $table->id(); $table->foreignId('candidate_id')->constrained('users')->cascadeOnDelete(); $table->string('file_path')->nullable(); $table->string('file_name')->nullable(); $table->text('summary')->nullable(); $table->json('parsed_data')->nullable(); $table->string('parse_status')->default('manual'); $table->timestamps(); });
        Schema::create('candidate_experiences', function (Blueprint $table) { $table->id(); $table->foreignId('candidate_id')->constrained('users')->cascadeOnDelete(); $table->string('company'); $table->string('title'); $table->date('started_at')->nullable(); $table->date('ended_at')->nullable(); $table->text('description')->nullable(); $table->timestamps(); });
        Schema::create('candidate_skills', function (Blueprint $table) { $table->id(); $table->foreignId('candidate_id')->constrained('users')->cascadeOnDelete(); $table->string('name'); $table->string('level')->nullable(); $table->timestamps(); $table->unique(['candidate_id','name']); });
        Schema::create('saved_jobs', function (Blueprint $table) { $table->id(); $table->foreignId('candidate_id')->constrained('users')->cascadeOnDelete(); $table->foreignId('job_id')->constrained()->cascadeOnDelete(); $table->timestamps(); $table->unique(['candidate_id','job_id']); });
        Schema::create('job_alerts', function (Blueprint $table) { $table->id(); $table->foreignId('candidate_id')->constrained('users')->cascadeOnDelete(); $table->string('name'); $table->string('keyword')->nullable(); $table->foreignId('job_category_id')->nullable()->constrained()->nullOnDelete(); $table->string('country_code',3)->nullable(); $table->string('location')->nullable(); $table->decimal('salary_min',12,2)->nullable(); $table->unsignedSmallInteger('experience_min')->nullable(); $table->string('frequency')->default('weekly'); $table->json('channels')->nullable(); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::create('messages', function (Blueprint $table) { $table->id(); $table->foreignId('sender_id')->constrained('users')->cascadeOnDelete(); $table->foreignId('recipient_id')->constrained('users')->cascadeOnDelete(); $table->foreignId('company_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('job_application_id')->nullable()->constrained()->nullOnDelete(); $table->string('type')->default('portal'); $table->string('subject')->nullable(); $table->text('body'); $table->timestamp('read_at')->nullable(); $table->timestamps(); });
        Schema::create('employer_ai_settings', function (Blueprint $table) { $table->id(); $table->foreignId('company_id')->unique()->constrained()->cascadeOnDelete(); $table->string('provider')->nullable(); $table->text('encrypted_api_key')->nullable(); $table->string('model')->nullable(); $table->boolean('is_enabled')->default(false); $table->timestamp('last_tested_at')->nullable(); $table->string('last_status')->default('not_configured'); $table->timestamps(); });
        Schema::create('candidate_archives', function (Blueprint $table) { $table->id(); $table->foreignId('company_id')->constrained()->cascadeOnDelete(); $table->foreignId('job_id')->constrained()->cascadeOnDelete(); $table->foreignId('candidate_id')->constrained('users')->cascadeOnDelete(); $table->foreignId('archived_by')->constrained('users')->cascadeOnDelete(); $table->string('reason'); $table->text('remarks')->nullable(); $table->timestamp('restored_at')->nullable(); $table->timestamps(); });
        Schema::create('communication_templates', function (Blueprint $table) { $table->id(); $table->string('type'); $table->string('name'); $table->string('subject')->nullable(); $table->longText('body'); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::create('communication_logs', function (Blueprint $table) { $table->id(); $table->foreignId('company_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('sender_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('recipient_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('channel'); $table->string('status')->default('queued'); $table->string('subject')->nullable(); $table->text('body'); $table->timestamp('sent_at')->nullable(); $table->text('error')->nullable(); $table->timestamps(); });
        Schema::create('security_logs', function (Blueprint $table) { $table->id(); $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $table->string('event'); $table->string('ip_address',45)->nullable(); $table->text('user_agent')->nullable(); $table->json('metadata')->nullable(); $table->timestamps(); });
        Schema::create('backup_logs', function (Blueprint $table) { $table->id(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->string('type'); $table->string('status')->default('queued'); $table->string('path')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); });
        Schema::table('api_integrations', function (Blueprint $table) { $table->string('webhook_secret_hint')->nullable()->after('encrypted_secret'); });
    }
    public function down(): void { Schema::table('api_integrations',fn(Blueprint $table)=>$table->dropColumn('webhook_secret_hint')); Schema::dropIfExists('backup_logs');Schema::dropIfExists('security_logs');Schema::dropIfExists('communication_logs');Schema::dropIfExists('communication_templates');Schema::dropIfExists('candidate_archives');Schema::dropIfExists('employer_ai_settings');Schema::dropIfExists('messages');Schema::dropIfExists('job_alerts');Schema::dropIfExists('saved_jobs');Schema::dropIfExists('candidate_skills');Schema::dropIfExists('candidate_experiences');Schema::dropIfExists('candidate_resumes'); }
};