<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Job;
use App\Models\JobApplication;
use App\Models\Offer;
use App\Models\Payment;
use App\Models\PlatformNotification;
use App\Models\Subscription;
use App\Models\User;
use Illuminate\View\View;

class CommandCenterController extends Controller
{
    public function show(string $section, ?string $view = null): View
    {
        abort_unless(auth()->user()?->hasRole('super-admin'), 403);

        $sections = $this->sections();
        abort_unless(isset($sections[$section]), 404);

        $activeView = $view ?? str($sections[$section]['items'][0])->slug();
        abort_unless(collect($sections[$section]['items'])->map(fn (string $item) => str($item)->slug())->contains($activeView), 404);

        return view('admin.command.show', [
            'section' => $section,
            'activeView' => $activeView,
            'definition' => $sections[$section],
            'metrics' => $this->metrics($section),
            'managementLink' => $this->managementLink($section, $activeView),
            'moduleSummary' => $this->moduleSummary($section, $activeView, $sections[$section]),
        ]);
    }

    private function moduleSummary(string $section, string $view, array $definition): array
    {
        return match ("{$section}/{$view}") {
            'employers/all-companies' => ['title' => 'Company directory', 'body' => 'Search and filter every employer, review company activity, and apply approval or access decisions.', 'state' => 'Live controls'],
            'employers/employer-notes' => ['title' => 'Employer notes', 'body' => 'Keep internal, admin-only notes attached to employer companies with author and timestamp history.', 'state' => 'Live controls'],
            'employers/employer-users' => ['title' => 'Employer access', 'body' => 'Review employer users by company and enable or disable their company access.', 'state' => 'Live controls'],
            'employers/employer-verification' => ['title' => 'Employer verification', 'body' => 'Review pending companies and apply verification decisions from the company directory.', 'state' => 'Live controls'],
            'employers/employer-documents' => ['title' => 'Employer documents', 'body' => 'Review, approve, reject, replace, and remove employer verification documents.', 'state' => 'Live controls'],
            'employers/employer-activity' => ['title' => 'Employer activity', 'body' => 'Inspect company-scoped audit events with actor, action, entity, and IP details.', 'state' => 'Live controls'],
            'job-seekers/all-job-seekers' => ['title' => 'Candidate directory', 'body' => 'Search, block, update, and delete job-seeker accounts.', 'state' => 'Live controls'],
            'job-seekers/new-registrations' => ['title' => 'New registrations', 'body' => 'Review candidates who registered during the last 30 days.', 'state' => 'Live controls'],
            'job-seekers/verified-candidates' => ['title' => 'Verified candidates', 'body' => 'Review candidates with verified email accounts.', 'state' => 'Live controls'],
            'job-seekers/incomplete-profiles' => ['title' => 'Incomplete profiles', 'body' => 'Find candidates who need profile completion follow-up.', 'state' => 'Live controls'],
            'job-seekers/complete-profiles' => ['title' => 'Complete profiles', 'body' => 'Review candidates whose profile completion has reached 100 percent.', 'state' => 'Live controls'],
            'job-seekers/blocked-candidates' => ['title' => 'Blocked candidates', 'body' => 'Restore or permanently remove blocked candidate accounts.', 'state' => 'Live controls'],
            'job-seekers/candidate-resumes' => ['title' => 'Candidate resumes', 'body' => 'Review parse status and remove obsolete candidate resumes.', 'state' => 'Live controls'],
            'job-seekers/candidate-skills' => ['title' => 'Candidate skills', 'body' => 'Add and remove skills attached to candidate profiles.', 'state' => 'Live controls'],
            'job-seekers/candidate-applications' => ['title' => 'Candidate applications', 'body' => 'Review applications and update their workflow status.', 'state' => 'Live controls'],
            'job-seekers/candidate-purchases' => ['title' => 'Candidate purchases', 'body' => 'Review candidate payments and update payment status.', 'state' => 'Live controls'],
            'job-seekers/candidate-login-history' => ['title' => 'Candidate login history', 'body' => 'Review immutable security events for job-seeker accounts.', 'state' => 'Read-only audit'],
            'job-seekers/candidate-notes' => ['title' => 'Candidate notes', 'body' => 'Create and remove internal notes attached to candidate applications.', 'state' => 'Live controls'],
            'jobs/all-jobs' => ['title' => 'Job directory', 'body' => 'Search, edit, approve, reject, archive, and delete job records.', 'state' => 'Live controls'],
            'jobs/pending-approval' => ['title' => 'Job approval queue', 'body' => 'Review draft jobs and publish or reject them.', 'state' => 'Live controls'],
            'jobs/approved-jobs', 'jobs/active-jobs' => ['title' => 'Active job inventory', 'body' => 'Review currently published jobs and their closing dates.', 'state' => 'Live controls'],
            'jobs/expired-jobs' => ['title' => 'Expired jobs', 'body' => 'Review jobs whose closing date has passed and archive or republish them.', 'state' => 'Live controls'],
            'jobs/rejected-jobs' => ['title' => 'Rejected jobs', 'body' => 'Review jobs rejected during administration.', 'state' => 'Live controls'],
            'jobs/featured-jobs', 'jobs/urgent-jobs', 'jobs/sponsored-jobs' => ['title' => 'Job promotion controls', 'body' => 'Manage featured, urgent, and sponsored visibility flags.', 'state' => 'Live controls'],
            'jobs/apply-soon-jobs' => ['title' => 'Apply soon jobs', 'body' => 'Review jobs closing within the next seven days.', 'state' => 'Live controls'],
            'jobs/paid-apply-jobs' => ['title' => 'Paid apply jobs', 'body' => 'Review jobs that charge an application fee.', 'state' => 'Live controls'],
            'jobs/external-jobs' => ['title' => 'External jobs', 'body' => 'Review jobs imported or marked as external sources.', 'state' => 'Live controls'],
            'jobs/archived-jobs' => ['title' => 'Archived jobs', 'body' => 'Review jobs removed from active operations.', 'state' => 'Live controls'],
            'recruitment/all-applications' => ['title' => 'Recruitment pipeline', 'body' => 'Search and manage every application across companies and jobs.', 'state' => 'Live controls'],
            'recruitment/new-applications' => ['title' => 'New applications', 'body' => 'Review applications that have not yet entered the pipeline.', 'state' => 'Live controls'],
            'recruitment/shortlisted' => ['title' => 'Shortlisted candidates', 'body' => 'Manage candidates selected for further review.', 'state' => 'Live controls'],
            'recruitment/contacted' => ['title' => 'Contacted candidates', 'body' => 'Track candidates who have been contacted by employers.', 'state' => 'Live controls'],
            'recruitment/interview-scheduled' => ['title' => 'Scheduled interviews', 'body' => 'Review applications with interviews scheduled.', 'state' => 'Live controls'],
            'recruitment/interviewed' => ['title' => 'Interviewed candidates', 'body' => 'Manage candidates who completed an interview.', 'state' => 'Live controls'],
            'recruitment/assessment' => ['title' => 'Assessments', 'body' => 'Track candidates in assessment review.', 'state' => 'Live controls'],
            'recruitment/selected' => ['title' => 'Selected candidates', 'body' => 'Manage selected candidates before offer completion.', 'state' => 'Live controls'],
            'recruitment/offer-prepared' => ['title' => 'Prepared offers', 'body' => 'Review offers prepared for candidates.', 'state' => 'Live controls'],
            'recruitment/offer-sent' => ['title' => 'Sent offers', 'body' => 'Track offers sent to candidates.', 'state' => 'Live controls'],
            'recruitment/offer-accepted' => ['title' => 'Accepted offers', 'body' => 'Track candidates who accepted their offers.', 'state' => 'Live controls'],
            'recruitment/joined' => ['title' => 'Joined candidates', 'body' => 'Review completed placements and joined candidates.', 'state' => 'Live controls'],
            'recruitment/rejected' => ['title' => 'Rejected candidates', 'body' => 'Review rejected applications and history.', 'state' => 'Live controls'],
            'recruitment/archived-candidates' => ['title' => 'Archived candidates', 'body' => 'Review archived applications and restore them through status changes.', 'state' => 'Live controls'],
            'external-data/external-candidates' => ['title' => 'External candidates', 'body' => 'Review candidate import batches received from authorized external sources.', 'state' => 'Live controls'],
            'external-data/external-jobs' => ['title' => 'External jobs', 'body' => 'Review jobs marked as external and their source companies.', 'state' => 'Live controls'],
            'external-data/partner-sources' => ['title' => 'Partner sources', 'body' => 'Create, pause, update, and remove authorized external data sources.', 'state' => 'Live controls'],
            'external-data/import-history' => ['title' => 'Import history', 'body' => 'Review all external candidate and job import batches.', 'state' => 'Live controls'],
            'external-data/sync-history' => ['title' => 'Sync history', 'body' => 'Review completed and running source synchronization batches.', 'state' => 'Live controls'],
            'external-data/failed-imports' => ['title' => 'Failed imports', 'body' => 'Review failed batches, error logs, and record counts.', 'state' => 'Live controls'],
            'subscriptions/packages', 'subscriptions/package-features', 'subscriptions/package-prices' => ['title' => 'Package controls', 'body' => 'Create and maintain package entitlements, features, prices, and validity.', 'state' => 'Live controls'],
            'subscriptions/active-subscriptions' => ['title' => 'Active subscriptions', 'body' => 'Review active employer subscriptions and current entitlements.', 'state' => 'Live controls'],
            'subscriptions/expired-subscriptions' => ['title' => 'Expired subscriptions', 'body' => 'Review expired subscriptions and update their lifecycle state.', 'state' => 'Live controls'],
            'subscriptions/expiring-soon' => ['title' => 'Expiring soon', 'body' => 'Review active subscriptions expiring within 30 days.', 'state' => 'Live controls'],
            'subscriptions/free-trials' => ['title' => 'Free trials', 'body' => 'Review subscriptions currently marked as trial access.', 'state' => 'Live controls'],
            'subscriptions/manual-assignments' => ['title' => 'Manual assignments', 'body' => 'Assign packages directly to companies and preserve entitlements.', 'state' => 'Live controls'],
            'subscriptions/subscription-history' => ['title' => 'Subscription history', 'body' => 'Review the complete subscription record history.', 'state' => 'Live controls'],
            'subscriptions/usage-credits' => ['title' => 'Usage credits', 'body' => 'Review subscription entitlements and usage-credit payloads.', 'state' => 'Live controls'],
            'payments/all-transactions' => ['title' => 'All transactions', 'body' => 'Search and manage every recorded payment transaction.', 'state' => 'Live controls'],
            'payments/employer-payments' => ['title' => 'Employer payments', 'body' => 'Review company-linked payment transactions.', 'state' => 'Live controls'],
            'payments/job-seeker-payments' => ['title' => 'Job seeker payments', 'body' => 'Review candidate-linked payment transactions.', 'state' => 'Live controls'],
            'payments/subscription-payments' => ['title' => 'Subscription payments', 'body' => 'Review payments connected to subscriptions.', 'state' => 'Live controls'],
            'payments/paid-job-applications' => ['title' => 'Paid job applications', 'body' => 'Review job-linked and paid-application transactions.', 'state' => 'Live controls'],
            'payments/add-on-payments' => ['title' => 'Add-on payments', 'body' => 'Review add-on purchase transactions.', 'state' => 'Live controls'],
            'payments/failed-payments' => ['title' => 'Failed payments', 'body' => 'Review and update failed payment records.', 'state' => 'Live controls'],
            'payments/refunds' => ['title' => 'Refunds', 'body' => 'Review transactions marked as refunded.', 'state' => 'Live controls'],
            'payments/payment-gateways' => ['title' => 'Payment gateways', 'body' => 'Review configured payment gateway integrations.', 'state' => 'Live controls'],
            'payments/payment-webhooks' => ['title' => 'Payment webhooks', 'body' => 'Review transactions containing gateway webhook payloads.', 'state' => 'Live controls'],
            'payments/payment-logs' => ['title' => 'Payment logs', 'body' => 'Review the complete payment transaction audit stream.', 'state' => 'Live controls'],
            'payments/invoices' => ['title' => 'Invoices', 'body' => 'Update and remove invoice records connected to payments.', 'state' => 'Live controls'],
            'interviews/all-interviews' => ['title' => 'Interview schedule', 'body' => 'Manage every scheduled, completed, cancelled, and rescheduled interview.', 'state' => 'Live controls'],
            'interviews/today-interviews' => ['title' => 'Today interviews', 'body' => 'Review interviews scheduled for today.', 'state' => 'Live controls'],
            'interviews/upcoming-interviews' => ['title' => 'Upcoming interviews', 'body' => 'Review future interviews that are not cancelled.', 'state' => 'Live controls'],
            'interviews/completed-interviews' => ['title' => 'Completed interviews', 'body' => 'Review interviews marked completed and capture feedback notes.', 'state' => 'Live controls'],
            'interviews/cancelled-interviews' => ['title' => 'Cancelled interviews', 'body' => 'Review cancelled interview records.', 'state' => 'Live controls'],
            'interviews/interview-modes' => ['title' => 'Interview modes', 'body' => 'Maintain reusable interview modes such as Zoom, phone, and in-person.', 'state' => 'Live controls'],
            'interviews/interview-feedback' => ['title' => 'Interview feedback', 'body' => 'Update interview notes and completion status from the schedule.', 'state' => 'Live controls'],
            'interviews/calendar-connections' => ['title' => 'Calendar connections', 'body' => 'Maintain calendar connection records for scheduling integrations.', 'state' => 'Live controls'],
            'analytics/hiring-funnel', 'analytics/application-conversion', 'analytics/interview-conversion', 'analytics/offer-acceptance-rate', 'analytics/average-time-to-hire', 'analytics/best-job-categories', 'analytics/employer-activity', 'analytics/candidate-growth', 'analytics/revenue-by-country', 'analytics/revenue-by-currency', 'analytics/ai-usage-by-employer' => ['title' => 'Analytics report', 'body' => 'Review live operational metrics calculated from platform records.', 'state' => 'Live controls'],
            'users-permissions/admin-users', 'users-permissions/admin-roles', 'users-permissions/permissions', 'users-permissions/activity-logs' => ['title' => 'Access control', 'body' => 'Review administrators, roles, permissions, and access activity.', 'state' => 'Live controls'],
            'audit-logs/admin-activity', 'audit-logs/employer-activity', 'audit-logs/candidate-activity', 'audit-logs/api-changes', 'audit-logs/payment-changes', 'audit-logs/security-logs' => ['title' => 'Audit activity', 'body' => 'Review security and platform activity records.', 'state' => 'Live controls'],
            'settings/portal-settings', 'settings/branding', 'settings/contact-information', 'settings/seo', 'settings/currency', 'settings/tax', 'settings/date-time', 'settings/countries', 'settings/languages', 'settings/email-configuration', 'settings/maintenance-mode', 'settings/terms', 'settings/privacy' => ['title' => 'Platform settings', 'body' => 'Maintain the selected settings record through the admin control center.', 'state' => 'Live controls'],
            'system/login-security', 'system/otp-settings', 'system/password-policy', 'system/session-settings', 'system/ip-blocking', 'system/failed-login-logs', 'system/api-rate-limits', 'system/file-upload-rules', 'system/import-export', 'system/system-logs', 'system/backup' => ['title' => 'System controls', 'body' => 'Review and maintain restricted system administration records.', 'state' => 'Live controls'],
            'communication/email-templates', 'communication/whatsapp-templates', 'communication/interview-templates', 'communication/offer-templates', 'communication/rejection-templates', 'communication/joining-templates' => ['title' => 'Communication templates', 'body' => 'Create, edit, activate, and remove reusable communication templates.', 'state' => 'Live controls'],
            'communication/communication-history' => ['title' => 'Communication history', 'body' => 'Review sent, queued, failed, and scheduled communication logs.', 'state' => 'Live controls'],
            'communication/scheduled-messages' => ['title' => 'Scheduled messages', 'body' => 'Review communication logs that are queued for delivery.', 'state' => 'Live controls'],
            'notifications/notification-dashboard' => ['title' => 'Notification dashboard', 'body' => 'Review notification volume, unread state, and delivery records.', 'state' => 'Live controls'],
            'notifications/notification-types' => ['title' => 'Notification types', 'body' => 'Review the notification types currently stored by the platform.', 'state' => 'Live controls'],
            'notifications/push-notifications', 'notifications/email-notifications', 'notifications/whatsapp-notifications' => ['title' => 'Channel notifications', 'body' => 'Review notifications recorded for the selected delivery channel.', 'state' => 'Live controls'],
            'notifications/admin-alerts', 'notifications/employer-alerts', 'notifications/job-seeker-alerts' => ['title' => 'Audience alerts', 'body' => 'Review alerts delivered to the selected user audience.', 'state' => 'Live controls'],
            'notifications/notification-sounds' => ['title' => 'Notification sounds', 'body' => 'Create and remove reusable notification sound records.', 'state' => 'Live controls'],
            'notifications/notification-history' => ['title' => 'Notification history', 'body' => 'Review and remove stored platform notifications.', 'state' => 'Live controls'],
            'cms/home-page', 'cms/home-sections', 'cms/specializations', 'cms/testimonials', 'cms/statistics', 'cms/marquee-job-ticker', 'cms/pages', 'cms/faq', 'cms/app-links' => ['title' => 'CMS content', 'body' => 'Create and remove structured content records used by the public website and app surfaces.', 'state' => 'Live controls'],
            'cms/sliders', 'cms/blog', 'cms/footer', 'cms/contact-information', 'cms/social-links' => ['title' => 'CMS management', 'body' => 'Manage the selected public-facing content through its dedicated admin editor.', 'state' => 'Live controls'],
            'cms/featured-jobs' => ['title' => 'Featured jobs', 'body' => 'Review live jobs marked as featured in the public marketplace.', 'state' => 'Live controls'],
            'cms/featured-employers' => ['title' => 'Featured employers', 'body' => 'Review verified companies available for public employer promotion.', 'state' => 'Live controls'],
            'ai-api/ai-dashboard' => ['title' => 'AI dashboard', 'body' => 'Review configured providers, enabled integrations, usage counters, and errors.', 'state' => 'Live controls'],
            'ai-api/global-ai-settings' => ['title' => 'Global AI settings', 'body' => 'Enable or disable platform feature flags without changing application code.', 'state' => 'Live controls'],
            'ai-api/platform-ai', 'ai-api/employer-byoai', 'ai-api/resume-parser', 'ai-api/embedding-api', 'ai-api/vector-database', 'ai-api/voice-api', 'ai-api/whatsapp-api', 'ai-api/email-api', 'ai-api/push-notifications', 'ai-api/google-calendar', 'ai-api/payment-api' => ['title' => 'AI/API integration', 'body' => 'Review the integration state, provider, environment, usage, and error status. Secrets remain encrypted at rest.', 'state' => 'Live controls'],
            'ai-api/api-usage' => ['title' => 'API usage', 'body' => 'Review usage counts and last request timestamps for configured integrations.', 'state' => 'Live controls'],
            'ai-api/api-errors' => ['title' => 'API errors', 'body' => 'Review and clear recorded integration errors.', 'state' => 'Live controls'],
            'ai-api/cost-monitoring' => ['title' => 'Cost monitoring', 'body' => 'Review monthly limits and usage counters for paid integrations.', 'state' => 'Live controls'],
            'job-masters/job-categories' => ['title' => 'Job categories', 'body' => 'Maintain categories used by public search, employer jobs, and candidate discovery.', 'state' => 'Live controls'],
            default => ['title' => $definition['title'].' workspace', 'body' => $definition['description'].' This module is currently represented by the configured navigation and linked operational screens.', 'state' => 'Configured module'],
        };
    }

    private function managementLink(string $section, string $view): ?array
    {
        return match ("{$section}/{$view}") {
            'employers/company-types' => ['label' => 'Manage Company Types', 'url' => route('admin.masters.index', 'company-types')],
            'employers/company-grades' => ['label' => 'Manage Company Grades', 'url' => route('admin.masters.index', 'company-grades')],
            'employers/all-companies' => ['label' => 'Manage All Companies', 'url' => route('admin.companies.index')],
            'employers/pending-approval' => ['label' => 'Review Pending Companies', 'url' => route('admin.companies.index', ['status' => 'pending'])],
            'employers/approved-companies' => ['label' => 'View Approved Companies', 'url' => route('admin.companies.index', ['status' => 'verified'])],
            'employers/suspended-companies' => ['label' => 'View Suspended Companies', 'url' => route('admin.companies.index', ['status' => 'suspended'])],
            'employers/expired-companies' => ['label' => 'View Expired Companies', 'url' => route('admin.companies.index', ['status' => 'expired'])],
            'employers/employer-users' => ['label' => 'Manage Employer Users', 'url' => route('admin.employer-users.index')],
            'employers/employer-verification' => ['label' => 'Open Verification Queue', 'url' => route('admin.companies.index', ['status' => 'pending'])],
            'employers/employer-documents' => ['label' => 'Review Employer Documents', 'url' => route('admin.employer-documents.index')],
            'employers/employer-activity' => ['label' => 'View Employer Activity', 'url' => route('admin.employer-activity.index')],
            'employers/employer-notes' => ['label' => 'Manage Employer Notes', 'url' => route('admin.employer-notes.index')],
            'job-seekers/all-job-seekers' => ['label' => 'Manage All Job Seekers', 'url' => route('admin.candidates.index', ['view' => 'all-job-seekers'])],
            'job-seekers/new-registrations' => ['label' => 'View New Registrations', 'url' => route('admin.candidates.index', ['view' => 'new-registrations'])],
            'job-seekers/verified-candidates' => ['label' => 'View Verified Candidates', 'url' => route('admin.candidates.index', ['view' => 'verified-candidates'])],
            'job-seekers/incomplete-profiles' => ['label' => 'View Incomplete Profiles', 'url' => route('admin.candidates.index', ['view' => 'incomplete-profiles'])],
            'job-seekers/complete-profiles' => ['label' => 'View Complete Profiles', 'url' => route('admin.candidates.index', ['view' => 'complete-profiles'])],
            'job-seekers/blocked-candidates' => ['label' => 'Manage Blocked Candidates', 'url' => route('admin.candidates.index', ['view' => 'blocked-candidates'])],
            'job-seekers/candidate-resumes' => ['label' => 'Manage Candidate Resumes', 'url' => route('admin.candidates.index', ['view' => 'candidate-resumes'])],
            'job-seekers/candidate-skills' => ['label' => 'Manage Candidate Skills', 'url' => route('admin.candidates.index', ['view' => 'candidate-skills'])],
            'job-seekers/candidate-applications' => ['label' => 'Manage Candidate Applications', 'url' => route('admin.candidates.index', ['view' => 'candidate-applications'])],
            'job-seekers/candidate-purchases' => ['label' => 'Manage Candidate Purchases', 'url' => route('admin.candidates.index', ['view' => 'candidate-purchases'])],
            'job-seekers/candidate-login-history' => ['label' => 'View Candidate Login History', 'url' => route('admin.candidates.index', ['view' => 'candidate-login-history'])],
            'job-seekers/candidate-notes' => ['label' => 'Manage Candidate Notes', 'url' => route('admin.candidates.index', ['view' => 'candidate-notes'])],
            'jobs/all-jobs' => ['label' => 'Manage All Jobs', 'url' => route('admin.jobs.index', ['view' => 'all-jobs'])],
            'jobs/pending-approval' => ['label' => 'Review Pending Jobs', 'url' => route('admin.jobs.index', ['view' => 'pending-approval'])],
            'jobs/approved-jobs' => ['label' => 'View Approved Jobs', 'url' => route('admin.jobs.index', ['view' => 'approved-jobs'])],
            'jobs/active-jobs' => ['label' => 'View Active Jobs', 'url' => route('admin.jobs.index', ['view' => 'active-jobs'])],
            'jobs/expired-jobs' => ['label' => 'View Expired Jobs', 'url' => route('admin.jobs.index', ['view' => 'expired-jobs'])],
            'jobs/rejected-jobs' => ['label' => 'View Rejected Jobs', 'url' => route('admin.jobs.index', ['view' => 'rejected-jobs'])],
            'jobs/featured-jobs' => ['label' => 'Manage Featured Jobs', 'url' => route('admin.jobs.index', ['view' => 'featured-jobs'])],
            'jobs/urgent-jobs' => ['label' => 'Manage Urgent Jobs', 'url' => route('admin.jobs.index', ['view' => 'urgent-jobs'])],
            'jobs/sponsored-jobs' => ['label' => 'Manage Sponsored Jobs', 'url' => route('admin.jobs.index', ['view' => 'sponsored-jobs'])],
            'jobs/apply-soon-jobs' => ['label' => 'View Apply Soon Jobs', 'url' => route('admin.jobs.index', ['view' => 'apply-soon-jobs'])],
            'jobs/paid-apply-jobs' => ['label' => 'Manage Paid Apply Jobs', 'url' => route('admin.jobs.index', ['view' => 'paid-apply-jobs'])],
            'jobs/external-jobs' => ['label' => 'Manage External Jobs', 'url' => route('admin.jobs.index', ['view' => 'external-jobs'])],
            'jobs/archived-jobs' => ['label' => 'Manage Archived Jobs', 'url' => route('admin.jobs.index', ['view' => 'archived-jobs'])],
            'recruitment/all-applications' => ['label' => 'Manage All Applications', 'url' => route('admin.recruitment.index', ['view' => 'all-applications'])],
            'recruitment/new-applications' => ['label' => 'View New Applications', 'url' => route('admin.recruitment.index', ['view' => 'new-applications'])],
            'recruitment/shortlisted' => ['label' => 'View Shortlisted Candidates', 'url' => route('admin.recruitment.index', ['view' => 'shortlisted'])],
            'recruitment/contacted' => ['label' => 'View Contacted Candidates', 'url' => route('admin.recruitment.index', ['view' => 'contacted'])],
            'recruitment/interview-scheduled' => ['label' => 'Manage Scheduled Interviews', 'url' => route('admin.recruitment.index', ['view' => 'interview-scheduled'])],
            'recruitment/interviewed' => ['label' => 'View Interviewed Candidates', 'url' => route('admin.recruitment.index', ['view' => 'interviewed'])],
            'recruitment/assessment' => ['label' => 'View Assessments', 'url' => route('admin.recruitment.index', ['view' => 'assessment'])],
            'recruitment/selected' => ['label' => 'View Selected Candidates', 'url' => route('admin.recruitment.index', ['view' => 'selected'])],
            'recruitment/offer-prepared' => ['label' => 'View Prepared Offers', 'url' => route('admin.recruitment.index', ['view' => 'offer-prepared'])],
            'recruitment/offer-sent' => ['label' => 'View Sent Offers', 'url' => route('admin.recruitment.index', ['view' => 'offer-sent'])],
            'recruitment/offer-accepted' => ['label' => 'View Accepted Offers', 'url' => route('admin.recruitment.index', ['view' => 'offer-accepted'])],
            'recruitment/joined' => ['label' => 'View Joined Candidates', 'url' => route('admin.recruitment.index', ['view' => 'joined'])],
            'recruitment/rejected' => ['label' => 'View Rejected Candidates', 'url' => route('admin.recruitment.index', ['view' => 'rejected'])],
            'recruitment/archived-candidates' => ['label' => 'Manage Archived Candidates', 'url' => route('admin.recruitment.index', ['view' => 'archived-candidates'])],
            'external-data/external-candidates' => ['label' => 'View External Candidates', 'url' => route('admin.external-data.index', ['view' => 'external-candidates'])],
            'external-data/external-jobs' => ['label' => 'View External Jobs', 'url' => route('admin.external-data.index', ['view' => 'external-jobs'])],
            'external-data/partner-sources' => ['label' => 'Manage Partner Sources', 'url' => route('admin.external-data.index', ['view' => 'partner-sources'])],
            'external-data/import-history' => ['label' => 'View Import History', 'url' => route('admin.external-data.index', ['view' => 'import-history'])],
            'external-data/sync-history' => ['label' => 'View Sync History', 'url' => route('admin.external-data.index', ['view' => 'sync-history'])],
            'external-data/failed-imports' => ['label' => 'Review Failed Imports', 'url' => route('admin.external-data.index', ['view' => 'failed-imports'])],
            'subscriptions/package-features' => ['label' => 'Manage Package Features', 'url' => route('admin.operations.index', 'packages')],
            'subscriptions/package-prices' => ['label' => 'Manage Package Prices', 'url' => route('admin.operations.index', 'packages')],
            'subscriptions/active-subscriptions' => ['label' => 'View Active Subscriptions', 'url' => route('admin.subscriptions.index', ['view' => 'active-subscriptions'])],
            'subscriptions/expired-subscriptions' => ['label' => 'View Expired Subscriptions', 'url' => route('admin.subscriptions.index', ['view' => 'expired-subscriptions'])],
            'subscriptions/expiring-soon' => ['label' => 'View Expiring Subscriptions', 'url' => route('admin.subscriptions.index', ['view' => 'expiring-soon'])],
            'subscriptions/free-trials' => ['label' => 'View Free Trials', 'url' => route('admin.subscriptions.index', ['view' => 'free-trials'])],
            'subscriptions/manual-assignments' => ['label' => 'Assign Subscriptions', 'url' => route('admin.subscriptions.index', ['view' => 'manual-assignments'])],
            'subscriptions/subscription-history' => ['label' => 'View Subscription History', 'url' => route('admin.subscriptions.index', ['view' => 'subscription-history'])],
            'subscriptions/usage-credits' => ['label' => 'View Usage Credits', 'url' => route('admin.subscriptions.index', ['view' => 'usage-credits'])],
            'payments/all-transactions' => ['label' => 'Manage All Transactions', 'url' => route('admin.payments.index', ['view' => 'all-transactions'])],
            'payments/employer-payments' => ['label' => 'View Employer Payments', 'url' => route('admin.payments.index', ['view' => 'employer-payments'])],
            'payments/job-seeker-payments' => ['label' => 'View Job Seeker Payments', 'url' => route('admin.payments.index', ['view' => 'job-seeker-payments'])],
            'payments/subscription-payments' => ['label' => 'View Subscription Payments', 'url' => route('admin.payments.index', ['view' => 'subscription-payments'])],
            'payments/paid-job-applications' => ['label' => 'View Paid Applications', 'url' => route('admin.payments.index', ['view' => 'paid-job-applications'])],
            'payments/add-on-payments' => ['label' => 'View Add-On Payments', 'url' => route('admin.payments.index', ['view' => 'add-on-payments'])],
            'payments/failed-payments' => ['label' => 'Review Failed Payments', 'url' => route('admin.payments.index', ['view' => 'failed-payments'])],
            'payments/refunds' => ['label' => 'Manage Refunds', 'url' => route('admin.payments.index', ['view' => 'refunds'])],
            'payments/payment-gateways' => ['label' => 'Manage Payment Gateways', 'url' => route('admin.payments.index', ['view' => 'payment-gateways'])],
            'payments/payment-webhooks' => ['label' => 'Review Payment Webhooks', 'url' => route('admin.payments.index', ['view' => 'payment-webhooks'])],
            'payments/payment-logs' => ['label' => 'View Payment Logs', 'url' => route('admin.payments.index', ['view' => 'payment-logs'])],
            'payments/invoices' => ['label' => 'Manage Invoices', 'url' => route('admin.payments.index', ['view' => 'invoices'])],
            'ai-api/ai-dashboard' => ['label' => 'Open AI Dashboard', 'url' => route('admin.ai-api.index', ['view' => 'ai-dashboard'])],
            'ai-api/global-ai-settings' => ['label' => 'Manage Global AI Settings', 'url' => route('admin.ai-api.index', ['view' => 'global-ai-settings'])],
            'ai-api/platform-ai' => ['label' => 'Manage Platform AI', 'url' => route('admin.ai-api.index', ['view' => 'platform-ai'])],
            'ai-api/employer-byoai' => ['label' => 'Manage Employer BYOAI', 'url' => route('admin.ai-api.index', ['view' => 'employer-byoai'])],
            'ai-api/resume-parser' => ['label' => 'Manage Resume Parser', 'url' => route('admin.ai-api.index', ['view' => 'resume-parser'])],
            'ai-api/embedding-api' => ['label' => 'Manage Embedding API', 'url' => route('admin.ai-api.index', ['view' => 'embedding-api'])],
            'ai-api/vector-database' => ['label' => 'Manage Vector Database', 'url' => route('admin.ai-api.index', ['view' => 'vector-database'])],
            'ai-api/voice-api' => ['label' => 'Manage Voice API', 'url' => route('admin.ai-api.index', ['view' => 'voice-api'])],
            'ai-api/whatsapp-api' => ['label' => 'Manage WhatsApp API', 'url' => route('admin.ai-api.index', ['view' => 'whatsapp-api'])],
            'ai-api/email-api' => ['label' => 'Manage Email API', 'url' => route('admin.ai-api.index', ['view' => 'email-api'])],
            'ai-api/push-notifications' => ['label' => 'Manage Push Notifications', 'url' => route('admin.ai-api.index', ['view' => 'push-notifications'])],
            'ai-api/google-calendar' => ['label' => 'Manage Google Calendar', 'url' => route('admin.ai-api.index', ['view' => 'google-calendar'])],
            'ai-api/payment-api' => ['label' => 'Manage Payment API', 'url' => route('admin.ai-api.index', ['view' => 'payment-api'])],
            'ai-api/api-usage' => ['label' => 'View API Usage', 'url' => route('admin.ai-api.index', ['view' => 'api-usage'])],
            'ai-api/api-errors' => ['label' => 'Review API Errors', 'url' => route('admin.ai-api.index', ['view' => 'api-errors'])],
            'ai-api/cost-monitoring' => ['label' => 'View Cost Monitoring', 'url' => route('admin.ai-api.index', ['view' => 'cost-monitoring'])],
            'interviews/all-interviews' => ['label' => 'Manage All Interviews', 'url' => route('admin.interviews.index', ['view' => 'all-interviews'])],
            'interviews/today-interviews' => ['label' => 'View Today Interviews', 'url' => route('admin.interviews.index', ['view' => 'today-interviews'])],
            'interviews/upcoming-interviews' => ['label' => 'View Upcoming Interviews', 'url' => route('admin.interviews.index', ['view' => 'upcoming-interviews'])],
            'interviews/completed-interviews' => ['label' => 'View Completed Interviews', 'url' => route('admin.interviews.index', ['view' => 'completed-interviews'])],
            'interviews/cancelled-interviews' => ['label' => 'View Cancelled Interviews', 'url' => route('admin.interviews.index', ['view' => 'cancelled-interviews'])],
            'interviews/interview-modes' => ['label' => 'Manage Interview Modes', 'url' => route('admin.interviews.index', ['view' => 'interview-modes'])],
            'interviews/interview-feedback' => ['label' => 'Manage Interview Feedback', 'url' => route('admin.interviews.index', ['view' => 'interview-feedback'])],
            'interviews/calendar-connections' => ['label' => 'Manage Calendar Connections', 'url' => route('admin.interviews.index', ['view' => 'calendar-connections'])],
            'job-masters/industries' => ['label' => 'Manage Industries', 'url' => route('admin.records.index', 'job-master-industries')],
            'job-masters/job-categories' => ['label' => 'Manage Job Categories', 'url' => route('admin.masters.index', 'job-categories')],
            'job-masters/job-subcategories' => ['label' => 'Manage Job Subcategories', 'url' => route('admin.records.index', 'job-master-subcategories')],
            'job-masters/job-roles' => ['label' => 'Manage Job Roles', 'url' => route('admin.records.index', 'job-master-roles')],
            'job-masters/skills' => ['label' => 'Manage Skills', 'url' => route('admin.records.index', 'job-master-skills')],
            'job-masters/experience-levels' => ['label' => 'Manage Experience Levels', 'url' => route('admin.records.index', 'job-master-experience-levels')],
            'job-masters/education-levels' => ['label' => 'Manage Education Levels', 'url' => route('admin.records.index', 'job-master-education-levels')],
            'job-masters/certifications' => ['label' => 'Manage Certifications', 'url' => route('admin.records.index', 'job-master-certifications')],
            'job-masters/job-types' => ['label' => 'Manage Job Types', 'url' => route('admin.records.index', 'job-master-job-types')],
            'job-masters/work-modes' => ['label' => 'Manage Work Modes', 'url' => route('admin.records.index', 'job-master-work-modes')],
            'job-masters/shifts' => ['label' => 'Manage Shifts', 'url' => route('admin.records.index', 'job-master-shifts')],
            'job-masters/salary-types' => ['label' => 'Manage Salary Types', 'url' => route('admin.records.index', 'job-master-salary-types')],
            'job-masters/notice-period' => ['label' => 'Manage Notice Periods', 'url' => route('admin.records.index', 'job-master-notice-periods')],
            'job-masters/employment-status' => ['label' => 'Manage Employment Status', 'url' => route('admin.records.index', 'job-master-employment-status')],
            'job-masters/visa-work-permit-types' => ['label' => 'Manage Visa Work Permit Types', 'url' => route('admin.records.index', 'job-master-visa-work-permit-types')],
            'subscriptions/packages' => ['label' => 'Manage Packages', 'url' => route('admin.operations.index', 'packages')],
            'cms/home-page' => ['label' => 'Manage Home Page', 'url' => route('admin.cms.index', ['view' => 'home-page'])],
            'cms/sliders' => ['label' => 'Manage Sliders', 'url' => route('admin.operations.index', 'sliders')],
            'cms/home-sections' => ['label' => 'Manage Home Sections', 'url' => route('admin.cms.index', ['view' => 'home-sections'])],
            'cms/specializations' => ['label' => 'Manage Specializations', 'url' => route('admin.cms.index', ['view' => 'specializations'])],
            'cms/featured-jobs' => ['label' => 'Manage Featured Jobs', 'url' => route('admin.cms.index', ['view' => 'featured-jobs'])],
            'cms/featured-employers' => ['label' => 'Manage Featured Employers', 'url' => route('admin.cms.index', ['view' => 'featured-employers'])],
            'cms/testimonials' => ['label' => 'Manage Testimonials', 'url' => route('admin.cms.index', ['view' => 'testimonials'])],
            'cms/statistics' => ['label' => 'Manage Statistics', 'url' => route('admin.cms.index', ['view' => 'statistics'])],
            'cms/marquee-job-ticker' => ['label' => 'Manage Marquee Ticker', 'url' => route('admin.cms.index', ['view' => 'marquee-job-ticker'])],
            'cms/blog' => ['label' => 'Manage Blog', 'url' => route('admin.blogs.index')],
            'cms/pages' => ['label' => 'Manage Pages', 'url' => route('admin.cms.index', ['view' => 'pages'])],
            'cms/faq' => ['label' => 'Manage FAQ', 'url' => route('admin.cms.index', ['view' => 'faq'])],
            'cms/footer' => ['label' => 'Manage Footer', 'url' => route('admin.site-settings.edit')],
            'cms/contact-information' => ['label' => 'Manage Contact Information', 'url' => route('admin.site-settings.edit')],
            'cms/social-links' => ['label' => 'Manage Social Links', 'url' => route('admin.site-settings.edit')],
            'cms/app-links' => ['label' => 'Manage App Links', 'url' => route('admin.cms.index', ['view' => 'app-links'])],
            'reports/employer-reports' => ['label' => 'Open Employer Reports', 'url' => route('admin.reports.index', ['view' => 'employer-reports'])],
            'reports/job-seeker-reports' => ['label' => 'Open Job Seeker Reports', 'url' => route('admin.reports.index', ['view' => 'job-seeker-reports'])],
            'reports/job-reports' => ['label' => 'Open Job Reports', 'url' => route('admin.reports.index', ['view' => 'job-reports'])],
            'reports/application-reports' => ['label' => 'Open Application Reports', 'url' => route('admin.reports.index', ['view' => 'application-reports'])],
            'reports/interview-reports' => ['label' => 'Open Interview Reports', 'url' => route('admin.reports.index', ['view' => 'interview-reports'])],
            'reports/offer-reports' => ['label' => 'Open Offer Reports', 'url' => route('admin.reports.index', ['view' => 'offer-reports'])],
            'reports/hiring-reports' => ['label' => 'Open Hiring Reports', 'url' => route('admin.reports.index', ['view' => 'hiring-reports'])],
            'reports/subscription-reports' => ['label' => 'Open Subscription Reports', 'url' => route('admin.reports.index', ['view' => 'subscription-reports'])],
            'reports/payment-reports' => ['label' => 'Open Payment Reports', 'url' => route('admin.reports.index', ['view' => 'payment-reports'])],
            'reports/revenue-reports' => ['label' => 'Open Revenue Reports', 'url' => route('admin.reports.index', ['view' => 'revenue-reports'])],
            'reports/ai-usage-reports' => ['label' => 'Open AI Usage Reports', 'url' => route('admin.reports.index', ['view' => 'ai-usage-reports'])],
            'reports/api-cost-reports' => ['label' => 'Open API Cost Reports', 'url' => route('admin.reports.index', ['view' => 'api-cost-reports'])],
            'reports/candidate-source-reports' => ['label' => 'Open Candidate Source Reports', 'url' => route('admin.reports.index', ['view' => 'candidate-source-reports'])],
            'reports/external-data-reports' => ['label' => 'Open External Data Reports', 'url' => route('admin.reports.index', ['view' => 'external-data-reports'])],
            'reports/country-reports' => ['label' => 'Open Country Reports', 'url' => route('admin.reports.index', ['view' => 'country-reports'])],
            'reports/category-reports' => ['label' => 'Open Category Reports', 'url' => route('admin.reports.index', ['view' => 'category-reports'])],
            'communication/email-templates' => ['label' => 'Manage Email Templates', 'url' => route('admin.communication.index', ['view' => 'email-templates'])],
            'communication/whatsapp-templates' => ['label' => 'Manage WhatsApp Templates', 'url' => route('admin.communication.index', ['view' => 'whatsapp-templates'])],
            'communication/interview-templates' => ['label' => 'Manage Interview Templates', 'url' => route('admin.communication.index', ['view' => 'interview-templates'])],
            'communication/offer-templates' => ['label' => 'Manage Offer Templates', 'url' => route('admin.communication.index', ['view' => 'offer-templates'])],
            'communication/rejection-templates' => ['label' => 'Manage Rejection Templates', 'url' => route('admin.communication.index', ['view' => 'rejection-templates'])],
            'communication/joining-templates' => ['label' => 'Manage Joining Templates', 'url' => route('admin.communication.index', ['view' => 'joining-templates'])],
            'communication/communication-history' => ['label' => 'View Communication History', 'url' => route('admin.communication.index', ['view' => 'communication-history'])],
            'communication/scheduled-messages' => ['label' => 'View Scheduled Messages', 'url' => route('admin.communication.index', ['view' => 'scheduled-messages'])],
            'notifications/notification-dashboard' => ['label' => 'Open Notification Dashboard', 'url' => route('admin.notifications.index', ['view' => 'notification-dashboard'])],
            'notifications/notification-types' => ['label' => 'View Notification Types', 'url' => route('admin.notifications.index', ['view' => 'notification-types'])],
            'notifications/push-notifications' => ['label' => 'View Push Notifications', 'url' => route('admin.notifications.index', ['view' => 'push-notifications'])],
            'notifications/email-notifications' => ['label' => 'View Email Notifications', 'url' => route('admin.notifications.index', ['view' => 'email-notifications'])],
            'notifications/whatsapp-notifications' => ['label' => 'View WhatsApp Notifications', 'url' => route('admin.notifications.index', ['view' => 'whatsapp-notifications'])],
            'notifications/admin-alerts' => ['label' => 'View Admin Alerts', 'url' => route('admin.notifications.index', ['view' => 'admin-alerts'])],
            'notifications/employer-alerts' => ['label' => 'View Employer Alerts', 'url' => route('admin.notifications.index', ['view' => 'employer-alerts'])],
            'notifications/job-seeker-alerts' => ['label' => 'View Job Seeker Alerts', 'url' => route('admin.notifications.index', ['view' => 'job-seeker-alerts'])],
            'notifications/notification-sounds' => ['label' => 'Manage Notification Sounds', 'url' => route('admin.notifications.index', ['view' => 'notification-sounds'])],
            'notifications/notification-history' => ['label' => 'View Notification History', 'url' => route('admin.notifications.index', ['view' => 'notification-history'])],
            'mobile-apps/job-seeker-app-settings' => ['label' => 'Manage Mobile App Settings', 'url' => route('admin.records.index', 'mobile-app-settings')],
            'support/all-queries' => ['label' => 'Manage All Queries', 'url' => route('admin.support-center.index', ['view' => 'all-queries'])],
            'support/new-queries' => ['label' => 'View New Queries', 'url' => route('admin.support-center.index', ['view' => 'new-queries'])],
            'support/open' => ['label' => 'View Open Queries', 'url' => route('admin.support-center.index', ['view' => 'open'])],
            'support/in-progress' => ['label' => 'View In-Progress Queries', 'url' => route('admin.support-center.index', ['view' => 'in-progress'])],
            'support/resolved' => ['label' => 'View Resolved Queries', 'url' => route('admin.support-center.index', ['view' => 'resolved'])],
            'support/closed' => ['label' => 'View Closed Queries', 'url' => route('admin.support-center.index', ['view' => 'closed'])],
            'support/assigned-agent' => ['label' => 'View Assigned Queries', 'url' => route('admin.support-center.index', ['view' => 'assigned-agent'])],
            'analytics/hiring-funnel' => ['label' => 'Open Hiring Funnel', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'hiring-funnel'])],
            'analytics/application-conversion' => ['label' => 'Open Application Conversion', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'application-conversion'])],
            'analytics/interview-conversion' => ['label' => 'Open Interview Conversion', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'interview-conversion'])],
            'analytics/offer-acceptance-rate' => ['label' => 'Open Offer Acceptance Rate', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'offer-acceptance-rate'])],
            'analytics/average-time-to-hire' => ['label' => 'Open Average Time to Hire', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'average-time-to-hire'])],
            'analytics/best-job-categories' => ['label' => 'Open Best Job Categories', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'best-job-categories'])],
            'analytics/employer-activity' => ['label' => 'Open Employer Activity', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'employer-activity'])],
            'analytics/candidate-growth' => ['label' => 'Open Candidate Growth', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'candidate-growth'])],
            'analytics/revenue-by-country' => ['label' => 'Open Revenue by Country', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'revenue-by-country'])],
            'analytics/revenue-by-currency' => ['label' => 'Open Revenue by Currency', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'revenue-by-currency'])],
            'analytics/ai-usage-by-employer' => ['label' => 'Open AI Usage by Employer', 'url' => route('admin.control-center.index', ['section' => 'analytics', 'view' => 'ai-usage-by-employer'])],
            'settings/portal-settings' => ['label' => 'Manage Portal Settings', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'portal-settings'])],
            'settings/branding' => ['label' => 'Manage Branding & Contact', 'url' => route('admin.site-settings.edit')],
            'settings/contact-information' => ['label' => 'Manage Contact Information', 'url' => route('admin.site-settings.edit')],
            'settings/seo' => ['label' => 'Manage SEO', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'seo'])],
            'settings/currency' => ['label' => 'Manage Currency', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'currency'])],
            'settings/tax' => ['label' => 'Manage Tax', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'tax'])],
            'settings/date-time' => ['label' => 'Manage Date Time', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'date-time'])],
            'settings/countries' => ['label' => 'Manage Countries', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'countries'])],
            'settings/languages' => ['label' => 'Manage Languages', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'languages'])],
            'settings/email-configuration' => ['label' => 'Manage Email Configuration', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'email-configuration'])],
            'settings/maintenance-mode' => ['label' => 'Manage Maintenance Mode', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'maintenance-mode'])],
            'settings/terms' => ['label' => 'Manage Terms', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'terms'])],
            'settings/privacy' => ['label' => 'Manage Privacy', 'url' => route('admin.control-center.index', ['section' => 'settings', 'view' => 'privacy'])],
            'system/login-security' => ['label' => 'Manage Login Security', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'login-security'])],
            'system/otp-settings' => ['label' => 'Manage OTP Settings', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'otp-settings'])],
            'system/password-policy' => ['label' => 'Manage Password Policy', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'password-policy'])],
            'system/session-settings' => ['label' => 'Manage Session Settings', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'session-settings'])],
            'system/ip-blocking' => ['label' => 'Manage IP Blocking', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'ip-blocking'])],
            'system/failed-login-logs' => ['label' => 'View Failed Login Logs', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'failed-login-logs'])],
            'system/api-rate-limits' => ['label' => 'Manage API Rate Limits', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'api-rate-limits'])],
            'system/file-upload-rules' => ['label' => 'Manage File Upload Rules', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'file-upload-rules'])],
            'system/import-export' => ['label' => 'Manage Import Export', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'import-export'])],
            'system/system-logs' => ['label' => 'View System Logs', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'system-logs'])],
            'system/backup' => ['label' => 'Manage Backups', 'url' => route('admin.control-center.index', ['section' => 'system', 'view' => 'backup'])],
            'users-permissions/admin-users' => ['label' => 'Manage Admin Users', 'url' => route('admin.control-center.index', ['section' => 'users-permissions', 'view' => 'admin-users'])],
            'users-permissions/admin-roles' => ['label' => 'Manage Roles', 'url' => route('admin.control-center.index', ['section' => 'users-permissions', 'view' => 'admin-roles'])],
            'users-permissions/permissions' => ['label' => 'Manage Permissions', 'url' => route('admin.control-center.index', ['section' => 'users-permissions', 'view' => 'permissions'])],
            'users-permissions/activity-logs' => ['label' => 'View Permission Activity', 'url' => route('admin.control-center.index', ['section' => 'users-permissions', 'view' => 'activity-logs'])],
            'audit-logs/admin-activity' => ['label' => 'View Admin Activity', 'url' => route('admin.control-center.index', ['section' => 'audit-logs', 'view' => 'admin-activity'])],
            'audit-logs/employer-activity' => ['label' => 'View Employer Activity', 'url' => route('admin.control-center.index', ['section' => 'audit-logs', 'view' => 'employer-activity'])],
            'audit-logs/candidate-activity' => ['label' => 'View Candidate Activity', 'url' => route('admin.control-center.index', ['section' => 'audit-logs', 'view' => 'candidate-activity'])],
            'audit-logs/api-changes' => ['label' => 'View API Changes', 'url' => route('admin.control-center.index', ['section' => 'audit-logs', 'view' => 'api-changes'])],
            'audit-logs/payment-changes' => ['label' => 'View Payment Changes', 'url' => route('admin.control-center.index', ['section' => 'audit-logs', 'view' => 'payment-changes'])],
            'audit-logs/security-logs' => ['label' => 'View Security Logs', 'url' => route('admin.control-center.index', ['section' => 'audit-logs', 'view' => 'security-logs'])],
            default => null,
        };
    }

    private function metrics(string $section): array
    {
        return match ($section) {
            'employers' => ['All Companies' => Company::count(), 'Pending Approval' => Company::where('status', 'pending')->count(), 'Approved' => Company::where('status', 'verified')->count()],
            'job-seekers' => ['Candidates' => User::whereHas('roles', fn ($query) => $query->where('slug', 'job-seeker'))->count(), 'Incomplete Profiles' => User::whereHas('candidateProfile', fn ($query) => $query->where('profile_completion', '<', 100))->count(), 'Applications' => JobApplication::count()],
            'jobs' => ['All Jobs' => Job::count(), 'Active Jobs' => Job::where('status', 'published')->count(), 'Pending Jobs' => Job::where('status', 'draft')->count()],
            'recruitment' => ['Applications' => JobApplication::count(), 'Interview Scheduled' => JobApplication::where('status', 'Interview Scheduled')->count(), 'Offers Sent' => Offer::where('status', 'sent')->count()],
            'subscriptions' => ['Packages' => \App\Models\Package::count(), 'Active Subscriptions' => Subscription::where('status', 'active')->count(), 'Expiring Soon' => Subscription::whereBetween('expires_at', [today(), today()->addDays(30)])->count()],
            'payments' => ['Transactions' => Payment::count(), 'Paid' => Payment::where('status', 'paid')->count(), 'Revenue' => Payment::where('status', 'paid')->sum('amount')],
            'notifications' => ['Notification History' => PlatformNotification::count(), 'Unread' => PlatformNotification::whereNull('read_at')->count(), 'Enabled Channels' => 1],
            'interviews' => ['Today' => \App\Models\Interview::whereDate('scheduled_at', today())->count(), 'Upcoming' => \App\Models\Interview::where('scheduled_at', '>', now())->count(), 'Completed' => \App\Models\Interview::where('status', 'completed')->count()],
            'offers' => ['All Offers' => Offer::count(), 'Sent' => Offer::where('status', 'sent')->count(), 'Accepted' => Offer::where('status', 'accepted')->count()],
            'ai-api' => ['Configured APIs' => \App\Models\ApiIntegration::count(), 'Enabled APIs' => \App\Models\ApiIntegration::where('is_enabled', true)->count(), 'API Errors' => \App\Models\ApiIntegration::whereNotNull('last_error')->count()],
            default => ['Configured' => count($this->sections()[$section]['items']), 'Active Users' => User::where('is_active', true)->count(), 'System Status' => 'Ready'],
        };
    }

    private function sections(): array
    {
        return [
            'employers' => ['title' => 'Employers', 'description' => 'Company approvals, verification, access, activity, packages, and internal notes.', 'items' => ['All Companies', 'Pending Approval', 'Approved Companies', 'Suspended Companies', 'Expired Companies', 'Company Types', 'Company Grades', 'Employer Users', 'Employer Verification', 'Employer Documents', 'Employer Activity', 'Employer Notes']],
            'job-seekers' => ['title' => 'Job Seekers', 'description' => 'Candidate profiles, verification, resumes, applications, purchases, and notes.', 'items' => ['All Job Seekers', 'New Registrations', 'Verified Candidates', 'Incomplete Profiles', 'Complete Profiles', 'Blocked Candidates', 'Candidate Resumes', 'Candidate Skills', 'Candidate Applications', 'Candidate Purchases', 'Candidate Login History', 'Candidate Notes']],
            'jobs' => ['title' => 'Jobs', 'description' => 'Central job approval, promotion, paid-apply, expiry, and archive controls.', 'items' => ['All Jobs', 'Pending Approval', 'Approved Jobs', 'Active Jobs', 'Expired Jobs', 'Rejected Jobs', 'Featured Jobs', 'Urgent Jobs', 'Sponsored Jobs', 'Apply Soon Jobs', 'Paid Apply Jobs', 'External Jobs', 'Archived Jobs']],
            'recruitment' => ['title' => 'Recruitment', 'description' => 'Cross-company ATS activity, candidate pipeline, interviews, offers, and placements.', 'items' => ['All Applications', 'New Applications', 'Shortlisted', 'Contacted', 'Interview Scheduled', 'Interviewed', 'Assessment', 'Selected', 'Offer Prepared', 'Offer Sent', 'Offer Accepted', 'Joined', 'Rejected', 'Archived Candidates']],
            'job-masters' => ['title' => 'Job Masters', 'description' => 'Master data that powers website, employer portal, job seeker portal, and mobile apps.', 'items' => ['Industries', 'Job Categories', 'Job Subcategories', 'Job Roles', 'Skills', 'Experience Levels', 'Education Levels', 'Certifications', 'Job Types', 'Work Modes', 'Shifts', 'Salary Types', 'Notice Period', 'Employment Status', 'Visa Work Permit Types']],
            'external-data' => ['title' => 'External Data', 'description' => 'Authorized feeds, partner imports, sources, sync history, failures, and visibility controls.', 'items' => ['External Candidates', 'External Jobs', 'Partner Sources', 'Import History', 'Sync History', 'Failed Imports']],
            'subscriptions' => ['title' => 'Subscriptions', 'description' => 'Packages, feature matrix, prices, trials, assignments, entitlements, and credits.', 'items' => ['Packages', 'Package Features', 'Package Prices', 'Active Subscriptions', 'Expired Subscriptions', 'Expiring Soon', 'Free Trials', 'Manual Assignments', 'Subscription History', 'Usage Credits']],
            'payments' => ['title' => 'Payments', 'description' => 'Employer and candidate transactions, refunds, gateway configuration, webhooks, and logs.', 'items' => ['All Transactions', 'Employer Payments', 'Job Seeker Payments', 'Subscription Payments', 'Paid Job Applications', 'Add-On Payments', 'Failed Payments', 'Refunds', 'Payment Gateways', 'Payment Webhooks', 'Payment Logs', 'Invoices']],
            'ai-api' => ['title' => 'AI & API', 'description' => 'Platform AI, BYOAI, resume parsing, vectors, messaging, costs, usage, and errors.', 'items' => ['AI Dashboard', 'Global AI Settings', 'Platform AI', 'Employer BYOAI', 'Resume Parser', 'Embedding API', 'Vector Database', 'Voice API', 'WhatsApp API', 'Email API', 'Push Notifications', 'Google Calendar', 'Payment API', 'API Usage', 'API Errors', 'Cost Monitoring']],
            'interviews' => ['title' => 'Interviews', 'description' => 'Interview schedules, modes, feedback, calendar links, and company activity.', 'items' => ['All Interviews', 'Today Interviews', 'Upcoming Interviews', 'Completed Interviews', 'Cancelled Interviews', 'Interview Modes', 'Interview Feedback', 'Calendar Connections']],
            'offers' => ['title' => 'Offers', 'description' => 'Draft, sent, accepted, rejected, expired offers and offer templates.', 'items' => ['All Offers', 'Draft Offers', 'Sent Offers', 'Accepted Offers', 'Rejected Offers', 'Expired Offers', 'Offer Templates']],
            'communication' => ['title' => 'Communication', 'description' => 'Managed email, WhatsApp, interview, offer, rejection, and joining templates.', 'items' => ['Email Templates', 'WhatsApp Templates', 'Interview Templates', 'Offer Templates', 'Rejection Templates', 'Joining Templates', 'Communication History', 'Scheduled Messages']],
            'notifications' => ['title' => 'Notifications', 'description' => 'Role-specific in-app, push, email, WhatsApp, alerts, sounds, and history.', 'items' => ['Notification Dashboard', 'Notification Types', 'Push Notifications', 'Email Notifications', 'WhatsApp Notifications', 'Admin Alerts', 'Employer Alerts', 'Job Seeker Alerts', 'Notification Sounds', 'Notification History']],
            'cms' => ['title' => 'CMS', 'description' => 'Home content, sliders, sections, specializations, blog, footer, social links, and app links.', 'items' => ['Home Page', 'Sliders', 'Home Sections', 'Specializations', 'Featured Jobs', 'Featured Employers', 'Testimonials', 'Statistics', 'Marquee Job Ticker', 'Blog', 'Pages', 'FAQ', 'Footer', 'Contact Information', 'Social Links', 'App Links']],
            'mobile-apps' => ['title' => 'Mobile Apps', 'description' => 'Independent Job Seeker and Employer Flutter app settings, versions, maintenance, and deep links.', 'items' => ['Job Seeker App Settings', 'Employer App Settings', 'App Slider', 'App Home Sections', 'Minimum App Version', 'Latest App Version', 'Force Update', 'Maintenance Mode', 'Android App URL', 'iOS App URL']],
            'support' => ['title' => 'Support', 'description' => 'Website, AI fallback, job seeker app, and employer app enquiries with agent workflows.', 'items' => ['All Queries', 'New Queries', 'Open', 'In Progress', 'Resolved', 'Closed', 'Assigned Agent']],
            'reports' => ['title' => 'Reports', 'description' => 'Operational reports with export-ready data categories.', 'items' => ['Employer Reports', 'Job Seeker Reports', 'Job Reports', 'Application Reports', 'Interview Reports', 'Offer Reports', 'Hiring Reports', 'Subscription Reports', 'Payment Reports', 'Revenue Reports', 'AI Usage Reports', 'API Cost Reports', 'Candidate Source Reports', 'External Data Reports', 'Country Reports', 'Category Reports']],
            'analytics' => ['title' => 'Analytics', 'description' => 'Hiring funnel, conversion, category performance, employer activity, growth, revenue, and AI usage.', 'items' => ['Hiring Funnel', 'Application Conversion', 'Interview Conversion', 'Offer Acceptance Rate', 'Average Time to Hire', 'Best Job Categories', 'Employer Activity', 'Candidate Growth', 'Revenue by Country', 'Revenue by Currency', 'AI Usage by Employer']],
            'users-permissions' => ['title' => 'Users & Permissions', 'description' => 'Admin users, roles, module permissions, activity, and least-privilege access management.', 'items' => ['Admin Users', 'Admin Roles', 'Permissions', 'Activity Logs']],
            'audit-logs' => ['title' => 'Audit Logs', 'description' => 'Admin, employer, candidate, API, payment, and security activity tracking.', 'items' => ['Admin Activity', 'Employer Activity', 'Candidate Activity', 'API Changes', 'Payment Changes', 'Security Logs']],
            'settings' => ['title' => 'Settings', 'description' => 'Portal identity, branding, SEO, localisation, tax, maintenance, terms, privacy, and contact settings.', 'items' => ['Portal Settings', 'Branding', 'Contact Information', 'SEO', 'Currency', 'Tax', 'Date Time', 'Countries', 'Languages', 'Email Configuration', 'Maintenance Mode', 'Terms', 'Privacy']],
            'system' => ['title' => 'System', 'description' => 'Security, imports, exports, queues, application logs, scheduled work, and restricted backups.', 'items' => ['Login Security', 'OTP Settings', 'Password Policy', 'Session Settings', 'IP Blocking', 'Failed Login Logs', 'API Rate Limits', 'File Upload Rules', 'Import Export', 'System Logs', 'Backup']],
        ];
    }
}