<x-admin-layout title="{{ str($view)->headline() }} | Luckyboss Admin" heading="{{ str($view)->headline() }}">
    <p style="color:#667085">Manage authorized external sources, imported records, synchronization history, and external jobs.</p>@if(session('success'))<p style="color:#027a48;font-weight:700">{{ session('success') }}</p>@endif
    @if($view === 'partner-sources')
        <form method="POST" action="{{ route('admin.external-data.sources.store') }}" class="admin-card" style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr auto;gap:12px;padding:16px;margin:18px 0">@csrf<input class="admin-input" style="margin:0" name="name" placeholder="Source name" required><input class="admin-input" style="margin:0" name="source_type" placeholder="Source type" required><input class="admin-input" style="margin:0" name="feed_type" value="manual" required><select class="admin-input" style="margin:0" name="status"><option value="active">Active</option><option value="paused">Paused</option><option value="failed">Failed</option></select><button class="admin-button">Add source</button></form>
        <section class="admin-card" style="padding:8px 18px;overflow:auto"><table class="admin-table"><thead><tr><th>Name</th><th>Type</th><th>Feed</th><th>Status</th><th>Limit</th><th>Action</th></tr></thead><tbody>@forelse($sources as $source)<tr><td>{{ $source->name }}</td><td>{{ $source->source_type }}</td><td>{{ $source->feed_type }}</td><td><form method="POST" action="{{ route('admin.external-data.sources.update', $source) }}" style="display:flex;gap:6px">@csrf @method('PUT')<input type="hidden" name="name" value="{{ $source->name }}"><input type="hidden" name="source_type" value="{{ $source->source_type }}"><input type="hidden" name="feed_type" value="{{ $source->feed_type }}"><select name="status" onchange="this.form.submit()"><option value="active" @selected($source->status === 'active')>Active</option><option value="paused" @selected($source->status === 'paused')>Paused</option><option value="failed" @selected($source->status === 'failed')>Failed</option></select></form></td><td>{{ $source->import_limit ?: 'Unlimited' }}</td><td><form method="POST" action="{{ route('admin.external-data.sources.destroy', $source) }}">@csrf @method('DELETE')<button style="border:0;background:none;color:#b42318">Delete</button></form></td></tr>@empty<tr><td colspan="6" style="padding:24px;color:#667085">No partner sources found.</td></tr>@endforelse</tbody></table></section>
    @elseif($view === 'external-jobs')
        <section class="admin-card" style="padding:8px 18px;overflow:auto"><table class="admin-table"><thead><tr><th>Job</th><th>Company</th><th>Status</th><th>Location</th><th>Updated</th></tr></thead><tbody>@forelse($jobs as $job)<tr><td>{{ $job->title }}</td><td>{{ $job->company->name }}</td><td>{{ str($job->status)->headline() }}</td><td>{{ $job->location ?: $job->country_code }}</td><td>{{ $job->updated_at->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="5" style="padding:24px;color:#667085">No external jobs found.</td></tr>@endforelse</tbody></table></section><div style="margin-top:18px">{{ $jobs->links() }}</div>
    @else
        @php($filteredBatches = collect($batches)->when($view === 'external-candidates', fn ($items) => $items->where('data_type', 'candidates'))->when($view === 'import-history', fn ($items) => $items)->when($view === 'sync-history', fn ($items) => $items->whereIn('status', ['running', 'completed']))->when($view === 'failed-imports', fn ($items) => $items->where('status', 'failed')->merge($items->where('records_failed', '>', 0))) )
        <section class="admin-card" style="padding:8px 18px;overflow:auto"><table class="admin-table" style="min-width:900px"><thead><tr><th>Source</th><th>Data type</th><th>Status</th><th>Received</th><th>Imported</th><th>Failed</th><th>Error</th><th>Actions</th></tr></thead><tbody>@forelse($filteredBatches as $batch)<tr><td>{{ $batch->externalSource?->name ?: 'Manual' }}</td><td>{{ str($batch->data_type)->headline() }}</td><td><form method="POST" action="{{ route('admin.external-data.batches.update', $batch) }}">@csrf @method('PUT')<input type="hidden" name="records_received" value="{{ $batch->records_received }}"><input type="hidden" name="records_imported" value="{{ $batch->records_imported }}"><input type="hidden" name="records_failed" value="{{ $batch->records_failed }}"><select name="status" onchange="this.form.submit()"><option value="queued" @selected($batch->status === 'queued')>Queued</option><option value="running" @selected($batch->status === 'running')>Running</option><option value="completed" @selected($batch->status === 'completed')>Completed</option><option value="failed" @selected($batch->status === 'failed')>Failed</option></select></form></td><td>{{ $batch->records_received }}</td><td>{{ $batch->records_imported }}</td><td>{{ $batch->records_failed }}</td><td>{{ $batch->error_log ?: '-' }}</td><td><form method="POST" action="{{ route('admin.external-data.batches.destroy', $batch) }}">@csrf @method('DELETE')<button style="border:0;background:none;color:#b42318">Delete</button></form></td></tr>@empty<tr><td colspan="8" style="padding:24px;color:#667085">No import batches found.</td></tr>@endforelse</tbody></table></section>
    @endif
</x-admin-layout>
